[2018-09-19T08:03:14.792] [ERROR] err - TypeError: This library (validator.js) validates strings only
    at assertString (D:\ManyKitHost\trunk\manykit\node_modules\validator\lib\util\assertString.js:11:11)
    at ltrim (D:\ManyKitHost\trunk\manykit\node_modules\validator\lib\ltrim.js:15:30)
    at Object.trim (D:\ManyKitHost\trunk\manykit\node_modules\validator\lib\trim.js:19:51)
    at login (D:\ManyKitHost\trunk\manykit\routes\func.js:255:38)
    at Layer.handle [as handle_request] (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:317:13)
    at D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:335:12)
    at next (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\ManyKitHost\trunk\manykit\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:275:17)
    at SendStream.onStatError (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:426:12)
    at next (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:736:16)
    at onstat (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:725:14)
[2018-09-19T10:59:20.558] [ERROR] err - { Error: Not Found
    at D:\ManyKitHost\trunk\manykit\app.js:308:15
    at Layer.handle [as handle_request] (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:317:13)
    at D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:335:12)
    at next (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\ManyKitHost\trunk\manykit\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:275:17)
    at SendStream.onStatError (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:426:12)
    at next (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:736:16)
    at onstat (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:152:21) status: 404 }
[2018-09-19T16:25:27.583] [ERROR] err - ReferenceError: qqname is not defined
    at publicSql.then (D:\ManyKitHost\trunk\manykit\routes\func.js:178:36)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2018-09-19T16:26:51.432] [ERROR] err - ReferenceError: qqname is not defined
    at publicSql.then (D:\ManyKitHost\trunk\manykit\routes\func.js:178:36)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2018-09-19T16:29:31.607] [ERROR] err - ReferenceError: qqname is not defined
    at publicSql.then (D:\ManyKitHost\trunk\manykit\routes\func.js:178:36)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2018-09-19T17:17:53.009] [ERROR] err - { Error: Not Found
    at D:\ManyKitHost\trunk\manykit\app.js:308:15
    at Layer.handle [as handle_request] (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:317:13)
    at D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:335:12)
    at next (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\ManyKitHost\trunk\manykit\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:275:17)
    at SendStream.onStatError (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:426:12)
    at next (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:736:16)
    at onstat (D:\ManyKitHost\trunk\manykit\node_modules\send\index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:152:21) status: 404 }
[2018-09-19T17:27:45.671] [ERROR] err - Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\response.js:730:10)
    at ServerResponse.send (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (D:\ManyKitHost\trunk\manykit\node_modules\express\lib\response.js:158:21)
    at Object.success (D:\ManyKitHost\trunk\manykit\common\responseResult.js:4:24)
    at publicSql.then (D:\ManyKitHost\trunk\manykit\routes\func.js:244:48)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
